### PR TITLE
Alias patch

### PR DESCRIPTION
**Pull request by rgmyr**
`'PHIS'` was still missing itself as an alias, so I added that. I didn't want to add a whole new test file, and I imagine it's not critical as these shouldn't be a problem moving forward, but this snippet could be a test for missing self references in `ALIAS`:

```python
missing_self_refs = [k for k, v in welly.defaults.ALIAS.items() if k not in v]
assert not missing_self_refs, f'ALIAS keys missing self references: {missing_self_refs}'
```

I also moved all of the "self references" to the front of the `ALIAS` lists. I think this makes more sense, since the exact mnemonic should take precedence over alternate aliases if both happen to be present

### CODE REVIEW

**Comment by rgmyr** [comment]
A quick test snippet for finding keys without self precedence:

```python
bad_self_precedence = [k for k, v in welly.defaults.ALIAS.items() if k != v[0]]
assert not bad_self_precedence, f'ALIAS keys without self-precedence: {bad_self_precedence}'
```

**Comment by kwinkunks** [comment]
I'm not sure self-references necessarily belong at the start of the lists, as some curves are more likely to be original or high-quality than those more generic names. In general, I'd understand HGR, say, to be a high-res or high-quality GR. And I'd probably take DT4P before DT, because if they both exist in a well, the DT is likely not original.

Having said that, I don't know that Ross Crain thought too hard about those, or if the current orderings are optimal. My thought was just to use his ordering, since they are the only published alias lists, AFAIK.

If we offer another ordering, maybe it should be another dictionary entirely.

Related: #117 -- then aliases would have some methods, like loading from files or handling various defaults.

**Comment by ThomasMGeo** [comment]
I think having another dictionary is fine, in the original state from R Crain, it was lacking a lot of the curves from the open source .las files from the UK, so would be nice to have a more complete list. 

Maybe have one has an import and R Crains list as the order?

**Comment by ThomasMGeo** [comment]
What about having an option for a strict R Crain list, expanded 'no warranty implied' list, and your own?

**Comment by kwinkunks** [comment]
Thought I'd better finally deal with this! I added PHIS to PHIS, but as discussed, won't move all of the names to the first position.

**Pull request closed without merging**
